def chart = api.newChartBuilder()
	.newPie()
		.getOptions()
			.setHideLegend(false)
			.setHideTooltips(false)
			.setVerticalLayout(false)
			.back()
		.addSeries()
			.setLabel('Series1')
			.setHideDataLabels(false)
			.setDatamart('DM.Transaction')
			.setCurrency('EUR')
			.addDimFilter('InvoiceDateYear', out.YearInput as String)
			.setHideOther(false)
			.setCategories('Country')
			.setSize('Quantity')
				.withTotal()
				.back()
			.withSortByCategories(SortType.ASCENDING)
			.setGeneratedQueryDto('{"datamart":"DM.Transaction","source":"DM.Transaction","name":null,"label":"Series1","rollup":true,"projections":{"x":{"alias":"x","label":"Country","expression":"Country","format":null},"y":{"alias":"y","label":"∑Quantity","expression":"SUM({field})","format":null,"name":"Quantity","advancedProjection":true,"function":null,"default":null,"formatString":"∑{field}","parameters":{"field":"Quantity","quantity":"Quantity","base":"ListPrice"}}},"filter":null,"aggregateFilter":null,"sortBy":["x"],"options":{"currency":"EUR","distribution":["y"]}}')
			.back()
		.getDictionary()
			.buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","key":"x","sectionLabel":"Series1","categoryLabel":"Projection","keyLabel":"Categories","defaultValue":"Country"},{"sectionIdx":1,"category":"PROJECTION","key":"m1","sectionLabel":"Series1","categoryLabel":"Projection","keyLabel":"Measure 1","defaultValue":"∑ResultPrice "},{"sectionIdx":1,"category":"PROJECTION","key":"y","sectionLabel":"Series1","categoryLabel":"Projection","keyLabel":"Size","defaultValue":"∑Quantity"}]')
			.back()
		.build()

return chart