def chart = api.newChartBuilder()
	.newDataTable()
		.getOptions()
			.setInitialDataGrouping(false)
			.setDisableDrilldown(false)
			.back()
		.addSeries()
			.setLabel('Series1')
			.setHideDataLabels(true)
			.setDatamart('DM.Transaction')
			.setCurrency('EUR')
			.addDimFilter('InvoiceDateYear', out.YearInput as String)
			.addGroupBy('Country')
			.addAdditionalMeasure()
				.setMeasure('Quantity')
				.setId(1)
				.withTotal()
				.back()
			.setGeneratedQueryDto('{"datamart":"DM.Transaction","source":"DM.Transaction","name":null,"label":"Series1","rollup":true,"projections":{"Country":{"alias":"Country","label":"Country","expression":"Country","format":null},"m1":{"alias":"m1","label":"∑Quantity","expression":"SUM({field})","format":null,"name":"Quantity","advancedProjection":true,"function":null,"default":null,"formatString":"∑{field}","parameters":{"field":"Quantity","quantity":"Quantity","base":"ListPrice"}}},"filter":null,"aggregateFilter":null,"sortBy":["Country"],"options":{"currency":"EUR"}}')
			.back()
		.getDictionary()
			.buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","key":"Country","sectionLabel":"Series1","categoryLabel":"Projection","keyLabel":"Country","defaultValue":"Country"},{"sectionIdx":1,"category":"PROJECTION","key":"m1","sectionLabel":"Series1","categoryLabel":"Projection","keyLabel":"Measure 1","defaultValue":"∑Quantity"}]')
			.back()
		.build()


return chart