def chart = api.newChartBuilder()
	.newScatter()
		.getOptions()
			.setHideLegend(false)
			.setHideTooltips(false)
			.setDiscretization(true)
			.back()
		.addSeries()
			.setLabel('Quantity vs Margin')
			.setDatamart('DM.Transaction')
			.setCurrency('EUR')
			.addDimFilter('InvoiceDateYear', out.YearInputParameter as String) // out(Element) or input(Input)
			.setAxisX('Quantity')
				.withTotal()
				.back()
			.setAxisY('Margin')
				.withPercent()
				.back()
			.setAggregationBy('CustomerId')
			.setBandBy('Region')
			.setShowBandByLegend(false)
			.setGeneratedQueryDto('{"datamart":"DM.Transaction","source":"DM.Transaction","name":null,"label":"Quantity vs Margin","rollup":true,"projections":{"x":{"alias":"x","label":"∑Quantity","expression":"SUM({field})","format":null,"name":"Quantity","advancedProjection":true,"function":null,"default":null,"formatString":"∑{field}","parameters":{"field":"Quantity","quantity":"Quantity","base":"ListPrice"}},"y":{"alias":"y","label":"∑Margin/ƒList Price (%)","expression":"100*SUM({field})/SUM({base})","format":null,"name":"Margin","advancedProjection":true,"function":null,"default":null,"formatString":"∑{field}/ƒ{base} (%)","parameters":{"field":"Margin","quantity":"Quantity","base":"ListPrice"}},"groupBy":{"alias":"groupBy","label":"Customer Id","expression":"CustomerId","format":null},"bandBy":{"alias":"bandBy","label":"Region","expression":"Region","format":null}},"filter":null,"aggregateFilter":null,"sortBy":[],"options":{"currency":"EUR","discretization":["x","y"],"distribution":["x","y"],"regression":["y","x"]}}')
			.back()
		.getDictionary()
			.buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","key":"groupBy","sectionLabel":"Quantity vs Margin","categoryLabel":"Projection","keyLabel":"Aggregation By","defaultValue":"Customer Id"},{"sectionIdx":1,"category":"PROJECTION","key":"bandBy","sectionLabel":"Quantity vs Margin","categoryLabel":"Projection","keyLabel":"Band By","defaultValue":"Region"},{"sectionIdx":1,"category":"PROJECTION","key":"x","sectionLabel":"Quantity vs Margin","categoryLabel":"Projection","keyLabel":"X Axis","defaultValue":"∑Quantity"},{"sectionIdx":1,"category":"PROJECTION","key":"y","sectionLabel":"Quantity vs Margin","categoryLabel":"Projection","keyLabel":"Y Axis","defaultValue":"∑Margin/ƒList Price (%)"}]')
			.back()
		.build()

return chart