def chart = api.newChartBuilder()
	.newWaterfall()
		.getOptions()
			.setHideLegend(false)
			.setHideTooltips(false)
			.back()
		.getSeries()
			.setLabel('Series1')
			.setHideDataLabels(false)
			.setDatamart('DM.Transaction')
			.setCurrency('EUR')
			.addDimFilter('InvoiceDateYear',  out.YearInputParameter as String)
			.getAggregation()
				.withTotal()
				.back()
			.addWaterfallColumn(WaterfallColumnType.RESULT, 'ListPrice', null)
			.addWaterfallColumn(WaterfallColumnType.SUBTRACT, 'Discount', null)
			.addWaterfallColumn(WaterfallColumnType.RESULT, 'InvoicePrice', null)
			.addWaterfallColumn(WaterfallColumnType.SUBTRACT, 'Cost', null)
			.addWaterfallColumn(WaterfallColumnType.RESULT, 'Margin', null)
			.setGeneratedQueryDto('{"datamart":"DM.Transaction","source":"DM.Transaction","name":null,"label":"Series1","rollup":true,"projections":{"pp_ListPrice":{"alias":"pp_ListPrice","label":"ListPrice","expression":"SUM({field})","format":null,"name":"ListPrice","advancedProjection":true,"function":null,"default":0,"formatString":"∑{field}","parameters":{"field":"ListPrice","quantity":"Quantity","base":"ListPrice"}},"na_Discount":{"alias":"na_Discount","label":"Discount","expression":"SUM({field})","format":null,"name":"Discount","advancedProjection":true,"function":null,"default":0,"formatString":"∑{field}","parameters":{"field":"Discount","quantity":"Quantity","base":"ListPrice"}},"pp_InvoicePrice":{"alias":"pp_InvoicePrice","label":"InvoicePrice","expression":"SUM({field})","format":null,"name":"InvoicePrice","advancedProjection":true,"function":null,"default":0,"formatString":"∑{field}","parameters":{"field":"InvoicePrice","quantity":"Quantity","base":"ListPrice"}},"na_Cost":{"alias":"na_Cost","label":"Cost","expression":"SUM({field})","format":null,"name":"Cost","advancedProjection":true,"function":null,"default":0,"formatString":"∑{field}","parameters":{"field":"Cost","quantity":"Quantity","base":"ListPrice"}},"pp_Margin":{"alias":"pp_Margin","label":"Margin","expression":"SUM({field})","format":null,"name":"Margin","advancedProjection":true,"function":null,"default":0,"formatString":"∑{field}","parameters":{"field":"Margin","quantity":"Quantity","base":"ListPrice"}}},"filter":null,"aggregateFilter":null,"sortBy":[],"options":{"currency":"EUR"}}')
			.back()
		.getDictionary()
			.buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","key":"x","sectionLabel":"Series 1","categoryLabel":"Projection","keyLabel":"X Axis","defaultValue":""},{"sectionIdx":1,"category":"PROJECTION","key":"y","sectionLabel":"Series 1","categoryLabel":"Projection","keyLabel":"Y Axis","defaultValue":""}]')
			.back()
		.build()

return chart